Connectivity check and multi-disk support in slapprepare

diff --git a/package/slapprepare/slapprepare/script/slapos b/package/slapprepare/slapprepare/script/slapos
--- a/package/slapprepare/slapprepare/script/slapos
+++ b/package/slapprepare/slapprepare/script/slapos
@@ -34,11 +34,31 @@ for service in rpcbind network-remotefs postfix ; do
 done
 
 IPV6CHECK=ipv6.google.com
+IPV4CHECK=google.com
+IPV6WAITTIME=5
 
-# Test ipv6 connectivity and if not working use openvpn 
+# Test ipv4/ipv6 connectivity and if not working use openvpn 
 # and wait for it to be ready
 /etc/init.d/openvpn stop
+
+ping -c 2 $IPV4CHECK
+while [ $? != 0 ]; do
+    sleep 5
+    ping -c 2 $IPV4CHECK
+done
+
+echo """Ipv4 connection ok"""
+
+# Wait for native ipv6 connection to be ready 
+i=0
 ping6 -c 2 $IPV6CHECK
+while [[ $? != 0 ]] && [[ $i < $IPV6WAITTIME ]]
+do
+    let i++
+    sleep 1
+    ping6 -c 2 $IPV6CHECK
+done
+
 if [[ $? != 0 ]]; then
     echo """ Starting openVPN """
     /etc/init.d/openvpn start
@@ -46,7 +66,7 @@ if [[ $? != 0 ]]; then
     while [[ $? != 0 ]]; do
         ping6 -c 2 $IPV6CHECK
     done
-    # Ask slapos to use openvpn as ipv6 provider                                                                                                                       
+    # Ask slapos to use openvpn as ipv6 provider      
     if [ ! -f /etc/slapos/openvpn-needed ]; then
         touch /etc/slapos/openvpn-needed
         echo "ipv6_interface = tapVPN" >> /etc/slapos/slapos.cfg
@@ -72,13 +92,14 @@ while :; do
   # software not detected, force forever installation
   echo -n "Installing SlapOS, log availble at ${SLAP_INSTALL_LOG}..."
   mkdir -p /opt/slapos
-  (python -S -c \
-    'import urllib2;print urllib2.urlopen("http://svn.zope.org/*checkout*/zc.buildout/trunk/bootstrap/bootstrap.py").read()' \
-    | python -S - -c /etc/slapos/software.cfg buildout:directory=/opt/slapos \
-    >> ${SLAP_INSTALL_LOG} 2>&1 && /opt/slapos/bin/buildout -c \
-    /etc/slapos/software.cfg buildout:directory=/opt/slapos >> \
-    ${SLAP_INSTALL_LOG} 2>&1 ) && (echo "done.") || (echo \
-    "failed, retrying, the last error was:." ; tail -n 20 ${SLAP_INSTALL_LOG} ; rm -f /opt/slapos/bin/slapformat)
+  #(python -S -c \
+  #  'import urllib2;print urllib2.urlopen("http://svn.zope.org/*checkout*/zc.buildout/trunk/bootstrap/bootstrap.py").read()' \
+  #  | python -S - -c /etc/slapos/software.cfg buildout:directory=/opt/slapos \
+  #  >> ${SLAP_INSTALL_LOG} 2>&1 && /opt/slapos/bin/buildout -c \
+  #  /etc/slapos/software.cfg buildout:directory=/opt/slapos >> \
+  #  ${SLAP_INSTALL_LOG} 2>&1 ) && (echo "done.") || (echo \
+  #  "failed, retrying, the last error was:." ; tail -n 20 ${SLAP_INSTALL_LOG} ; rm -f /opt/slapos/bin/slapformat)
+  rpm --install --force /etc/slapos/slapos*.rpm
 done
 
 # Create PKI repository
